<button hidden id="page_goods_featuresItems" value="<%=session.getAttribute("page.goods.featuresItems")%>"/>
<button hidden id="page_goods_addToCart" value="<%=session.getAttribute("page.goods.addToCart")%>"/>
<button hidden id="page_goods_prev" value="<%=session.getAttribute("page.goods.prev")%>"/>
<button hidden id="page_goods_next" value="<%=session.getAttribute("page.goods.next")%>"/>
<button hidden id="page_goods_name_id1" value="<%=session.getAttribute("page.goods.name.id1")%>"/>
<button hidden id="page_goods_name_id2" value="<%=session.getAttribute("page.goods.name.id2")%>"/>
<button hidden id="page_goods_name_id3" value="<%=session.getAttribute("page.goods.name.id3")%>"/>
<button hidden id="page_goods_name_id4" value="<%=session.getAttribute("page.goods.name.id4")%>"/>
<button hidden id="page_goods_name_id5" value="<%=session.getAttribute("page.goods.name.id5")%>"/>
<button hidden id="page_goods_name_id6" value="<%=session.getAttribute("page.goods.name.id6")%>"/>
<button hidden id="page_goods_name_id7" value="<%=session.getAttribute("page.goods.name.id7")%>"/>
<button hidden id="page_goods_name_id8" value="<%=session.getAttribute("page.goods.name.id8")%>"/>
<button hidden id="page_goods_name_id9" value="<%=session.getAttribute("page.goods.name.id9")%>"/>
<button hidden id="page_goods_name_id10" value="<%=session.getAttribute("page.goods.name.id10")%>"/>
<button hidden id="page_goods_name_id11" value="<%=session.getAttribute("page.goods.name.id11")%>"/>
<button hidden id="page_cart_confirmation" value="<%=session.getAttribute("page.cart.confirmation")%>"/>